derrores = {
    "codigo_error": [
        1,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        15,
        16,
        17,
        20,
        21,
        22,
        23,
        24,
        31,
        32,
        33,
        34,
        35,
        36,
        41,
        42,
        43,
        51,
        53,
        61,
        62,
        63,
        64,
        71,
        72,
        73,
        74,
        75,
        76,
        77,
        78,
        79,
    ],
    "tipo_error": [
        "MAN",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
        "CAL",
    ],
    "descripcion": [
        "ERROR EN EL SERVIDOR",
        "ERROR EN EL SERVIDOR",
        "LA REFERENCIA CATASTRAL ES OBLIGATORIA",
        "LA REFERENCIA CATASTRAL DEBE TENER 14,18 o 20 POSICIONES",
        "LA REFERENCIA CATASTRAL NO ESTÁ CORRECTAMENTE FORMADA",
        "NO EXISTE NINGÚN INMUEBLE CON LOS PARÁMETROS INDICADOS",
        "ERROR AL CONSULTAR LA REFERENCIA",
        "LA REFERENCIA CATASTRAL DEBE SER UNA COMBINACIÓN DE LETRAS Y NÚMEROS HASTA UN TOTAL DE 20 CARACTERES.",
        "EL HUSO GEOGRÁFICO DEBE SER UNA SECUENCIA DE HASTA 10 CARACTERES.",
        "LA REFERENCIA CATASTRAL NO EXISTE",
        "ERROR AL CONSULTAR LA REFERENCIA",
        "LA PROVINCIA ES OBLIGATORIA",
        "LA PROVINCIA NO EXISTE",
        "LA PROVINCIA DEBE SER UNA SECUENCIA DE HASTA 25 CARACTERES.",
        "ERROR AL BUSCAR LAS COORDENADAS",
        "PARA ESAS COORDENADAS NO HAY REFERENCIA DISPONIBLE",
        "LA REFERENCIA CATASTRAL ES OBLIGATORIA",
        "ERROR AL CONSULTAR EL MUNICIPIO",
        "EL MUNICIPIO ES OBLIGATORIO.",
        "EL MUNICIPIO NO EXISTE.",
        "EL CÓDIGO DE MUNICIPIO DEBE SER UNA SECUENCIA DE HASTA 3 DÍGITOS.",
        "EL MUNICIPIO DEBE SER UNA SECUENCIA DE HASTA 40 CARACTERES.",
        "EL TIPO DE VIA ES OBLIGATORIO.",
        "LA VIA ES OBLIGATORIA.",
        "LA VÍA NO EXISTE",
        "EL NOMBRE DE LA VÍA DEBE SER UNA SECUENCIA DE HASTA 25 CARACTERES",
        "EL TIPO DE VÍA DEBE SER UNA SECUENCIA DE HASTA 5 CARACTERES",
        "EL CÓDIGO DE VÍA DEBE SER UNA SECUENCIA DE HASTA 5 DÍGITOS.",
        "EL NÚMERO ES OBLIGATORIO.",
        "EL NÚMERO DEBE SER UNA SECUENCIA DE HASTA 4 DÍGITOS.",
        "EL NUMERO NO EXISTE",
        "EL BLOQUE DEBE SER UNA SECUENCIA DE HASTA 4 CARACTERES.",
        "ERROR EN EL FORMATO DEL BLOQUE, ESCALERA, PLANTA O PUERTA",
        "EL POLIGONO ES OBLIGATORIO",
        "LA PARCELA ES OBLIGATORIA",
        "EL POLÍGONO DEBE SER UNA SECUENCIA DE HASTA 3 DÍGITOS.",
        "LA PARCELA DEBE SER UNA SECUENCIA DE HASTA 5 DÍGITOS.",
        "ERROR AL RECUPERAR EL DOMICILIO",
        "NO HAY CARTOGRAFIA DISPONIBLE",
        "ERROR AL BUSCAR LA PARCELA",
        "ERROR AL GENERAR EL RETORNO",
        "EL CAMPO SRS ES OBLIGATORIO",
        "LA COORDENADA X OBLIGATORIA",
        "LA COORDENADA X DEBE SER UN VALOR NUMÉRICO",
        "LA COORDENADA Y DEBE SER UN VALOR NUMÉRICO",
        "LA COORDENADA Y OBLIGATORIA",
    ],
}

codigos_vias = {
    "codigo_via": [
        "AC",
        "AG",
        "AL",
        "AN",
        "AR",
        "AU",
        "AV",
        "AY",
        "BJ",
        "BL",
        "BO",
        "BQ",
        "BR",
        "CA",
        "CG",
        "CH",
        "CI",
        "CJ",
        "CL",
        "CM",
        "CN",
        "CO",
        "CP",
        "CR",
        "CS",
        "CT",
        "CU",
        "CY",
        "CZ",
        "DE",
        "DP",
        "DS",
        "ED",
        "EM",
        "EN",
        "EP",
        "ER",
        "ES",
        "EX",
        "FC",
        "FN",
        "GL",
        "GR",
        "GV",
        "HT",
        "JR",
        "LA",
        "LD",
        "LG",
        "MA",
        "MC",
        "ML",
        "MN",
        "MS",
        "MT",
        "MZ",
        "PB",
        "PC",
        "PD",
        "PI",
        "PJ",
        "PL",
        "PM",
        "PQ",
        "PR",
        "PS",
        "PT",
        "PU",
        "PZ",
        "QT",
        "RA",
        "RB",
        "RC",
        "RD",
        "RM",
        "RP",
        "RR",
        "RU",
        "SA",
        "SC",
        "SD",
        "SL",
        "SN",
        "SU",
        "TN",
        "TO",
        "TR",
        "UR",
        "VA",
        "VD",
        "VI",
        "VL",
        "VR",
    ],
    "descripcion": [
        "ACCESO",
        "AGREGADO",
        "ALDEA, ALAMEDA",
        "ANDADOR",
        "AREA, ARRABAL",
        "AUTOPISTA",
        "AVENIDA",
        "ARROYO",
        "BAJADA",
        "BLOQUE",
        "BARRIO",
        "BARRANQUIL",
        "BARRANCO",
        "CAÑADA",
        "COLEGIO, CIGARRAL",
        "CHALET",
        "CINTURON",
        "CALLEJA, CALLEJON",
        "CALLE",
        "CAMINO, CARMEN",
        "COLONIA",
        "CONCEJO, COLEGIO",
        "CAMPA, CAMPO",
        "CARRETERA, CARRERA",
        "CASERIO",
        "CUESTA, COSTANILLA",
        "CONJUNTO",
        "CALEYA",
        "CALLIZO",
        "DETRÁS",
        "DIPUTACION",
        "DISEMINADOS",
        "EDIFICIOS",
        "EXTRAMUROS",
        "ENTRADA, ENSANCHE",
        "ESPALDA",
        "EXTRARRADIO",
        "ESCALINATA",
        "EXPLANADA",
        "FERROCARRIL",
        "FINCA",
        "GLORIETA",
        "GRUPO",
        "GRAN VIA",
        "HUERTA, HUERTO",
        "JARDINES",
        "LAGO",
        "LADO, LADERA",
        "LUGAR",
        "MALECON",
        "MERCADO",
        "MUELLE",
        "MUNICIPIO",
        "MASIAS",
        "MONTE",
        "MANZANA",
        "POBLADO",
        "PLACETA",
        "PARTIDA",
        "PARTICULAR",
        "PASAJE, PASADIZO",
        "POLIGONO",
        "PARAMO",
        "PARROQUIA, PARQUE",
        "PROLONGACION, CONTINUAC.",
        "PASEO",
        "PUENTE",
        "PASADIZO",
        "PLAZA",
        "QUINTA",
        "RACONADA",
        "RAMBLA",
        "RINCON, RINCONA",
        "RONDA",
        "RAMAL",
        "RAMPA",
        "RIERA",
        "RUA",
        "SALIDA",
        "SECTOR",
        "SENDA",
        "SOLAR",
        "SALON",
        "SUBIDA",
        "TERRENOS",
        "TORRENTE",
        "TRAVESIA",
        "URBANIZACION",
        "VALLE",
        "VIADUCTO",
        "VIA",
        "VIAL",
        "VEREDA",
    ],
}
